# Generated by Django 3.1.2 on 2020-10-17 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='modfify',
            new_name='modify',
        ),
    ]
